[package]
name = "wormsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "wormsim"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22"
numpy = "0.22"
rand = "0.8.5"
dict_derive = "0.6"
