language = {
    "ja": {
        "title": "線虫シミュレーター",
        "description": """この線虫シミュレーターは、*Caenorhabditis elegans*（*C. elegans*）が示す塩濃度記憶に依存した塩走性を再現するために作成されました。モデルは以下の論文に基づき構築されています。""",
        "paper_reference": """Hironaka, M., & Sumi, T. (2024). *A neural network model that generates salt concentration memory-dependent chemotaxis in Caenorhabditis elegans*. [DOI: 10.1101/2024.11.04.621960](https://doi.org/10.1101/2024.11.04.621960)""",
        "usage_info": """使用方法
1. 下のタブから、線虫の個体や塩濃度関数を選択します。
2. 必要に応じてパラメータを調整します。  
3. [シミュレーションを実行]を押すことで、アニメーションが表示されます。""",
        "simulation_environment": ":red-background[シミュレーション環境]（パラメータの変更がリアルタイムで反映されます。）",
        "tab_names": ["線虫の個体", "塩濃度関数", "その他の設定"],
        "select_worm_label": "線虫の個体を選択してください。",
        "select_worm_options": [
            "高塩濃度環境で育成した個体",
            "低塩濃度環境で育成した個体",
            "高塩濃度環境で育成した個体(飢餓)",
            "低塩濃度環境で育成した個体(飢餓)",
        ],
        "select_worm_help": "線虫は培養中に記憶した塩濃度に基づき、現在の環境における嗜好行動を示します。",
        "neural_circuit": "神経回路：",
        "expander_image_label": "画像を表示",
        "image_caption": "白い円は化学感覚ニューロン、灰色の円は介在ニューロン、黒い円は運動ニューロンを表しています。青い矢印と赤い平らな矢印は、それぞれ興奮性と抑制性のシナプス接続を示しています。緑の線は電気的ギャップ結合を示しています。また、接続の太さはそれぞれの結合の強度を示しています。",
        "select_concentration_label": "塩濃度関数を選択してください。",
        "select_concentration_options": [
            "ガウス分布（ピーク１つ）",
            "ガウス分布（ピーク２つ）",
        ],
        "select_concentration_help": "論文中では、ガウス分布（ピーク１つ）の関数のみ使用されています。",
        "concentration_function": "塩濃度関数：",
        "concentration_function_1": "$C(x,y)=C_0e^{-\\frac{(x-x_{peak})^2+(y-y_{peak})^2}{2\\lambda^2}}$",
        "concentration_function_2": "$C(x,y)=C_0[e^{-\\frac{(x-x_{peak})^2+(y-y_{peak})^2}{2\\lambda^2}}-e^{-\\frac{(x+x_{peak})^2+(y+y_{peak})^2}{2\\lambda^2}}]$",
        "slider_x_peak": "$x_{peak}$ /cm",
        "slider_x_peak_help": "Gradient Peakのx座標",
        "slider_y_peak": "$y_{peak}$ /cm",
        "slider_y_peak_help": "Gradient Peakのy座標",
        "slider_c_0": "$C_0$ /mM",
        "slider_c_0_help": "塩濃度の最大値を決めるパラメータ",
        "slider_lambda": "$\\lambda$ /cm",
        "slider_lambda_help": "塩濃度の広がり方を決めるパラメータ",
        "slider_mu_0": "進行方向 /rad",
        "slider_mu_0_help": "線虫のスタート地点での進行方向",
        "slider_simulation_time": "シミュレーション時間 /s",
        "slider_simulation_time_help": "シミュレーション内で経過する時間",
        "animation_quality_label": "アニメーションの描画精度",
        "animation_quality_options": ["低レベル", "中レベル", "高レベル"],
        "animation_quality_help": "レベルが低いほどフレーム数が減少する",
        "dialog_title": "シミュレーション結果",
        "spinner_message": "実行中...",
        "success_message": "画面左下にある&#9654;からアニメーションを再生できます。",
        "simulation_button": "シミュレーションを実行",
    },
    "en": {
        "title": "*C. elegans* Simulator",
        "description": """This *C. elegans* simulator was developed to reproduce the salt concentration memory-dependent chemotaxis exhibited by *Caenorhabditis elegans*. The model is based on the following paper:""",
        "paper_reference": """Hironaka, M., & Sumi, T. (2024). *A neural network model that generates salt concentration memory-dependent chemotaxis in Caenorhabditis elegans*. [DOI: 10.1101/2024.11.04.621960](https://doi.org/10.1101/2024.11.04.621960)""",
        "usage_info": """How to Use:
1. Select the *C. elegans* individual and salt concentration function from the tabs below.
2. Change the parameters.  
3. Click [Run Simulation] to display the animation.""",
        "simulation_environment": ":red-background[Simulation Environment] (Parameter changes are reflected in real-time.)",
        "tab_names": [
            "*C. elegans* Individual",
            "Salt Concentration Function",
            "Other Settings",
        ],
        "select_worm_label": "Select a *C. elegans* individual.",
        "select_worm_options": [
            "Individual cultivated in high-salt environment",
            "Individual cultivated in low-salt environment",
            "Individual cultivated in high-salt environment (starvation)",
            "Individual cultivated in low-salt environment (starvation)",
        ],
        "select_worm_help": "*C. elegans* exhibits preference behavior based on the salt concentration it memorized during cultivation.",
        "neural_circuit": "Neural Circuit:",
        "expander_image_label": "Show Image",
        "image_caption": "White circles represent chemosensory neurons, gray circles represent interneurons, and black circles represent motor neurons. Blue arrows and red flat arrows indicate excitatory and inhibitory synaptic connections, respectively. Green lines represent electrical gap junctions. The thickness of the connections indicates the strength of each connection.",
        "select_concentration_label": "Select a salt concentration function.",
        "select_concentration_options": [
            "Gaussian Distribution (Single Peak)",
            "Gaussian Distribution (Two Peaks)",
        ],
        "select_concentration_help": "In the paper, only the Gaussian distribution (single peak) function is used.",
        "concentration_function": "Salt Concentration Function:",
        "concentration_function_1": "$C(x,y)=C_0e^{-\\frac{(x-x_{peak})^2+(y-y_{peak})^2}{2\\lambda^2}}$",
        "concentration_function_2": "$C(x,y)=C_0[e^{-\\frac{(x-x_{peak})^2+(y-y_{peak})^2}{2\\lambda^2}}-e^{-\\frac{(x+x_{peak})^2+(y+y_{peak})^2}{2\\lambda^2}}]$",
        "slider_x_peak": "$x_{peak}$ /cm",
        "slider_x_peak_help": "X-coordinate of the gradient peak",
        "slider_y_peak": "$y_{peak}$ /cm",
        "slider_y_peak_help": "Y-coordinate of the gradient peak",
        "slider_c_0": "$C_0$ /mM",
        "slider_c_0_help": "Parameter determining the maximum salt concentration",
        "slider_lambda": "$\\lambda$ /cm",
        "slider_lambda_help": "Parameter determining the spread of the salt concentration",
        "slider_mu_0": "Initial Direction /rad",
        "slider_mu_0_help": "The initial movement direction of *C. elegans* at the starting point",
        "slider_simulation_time": "Simulation Time /s",
        "slider_simulation_time_help": "Elapsed time within the simulation",
        "animation_quality_label": "Animation Rendering Quality",
        "animation_quality_options": ["Low", "Medium", "High"],
        "animation_quality_help": "Lower levels reduce the number of frames",
        "dialog_title": "Simulation Results",
        "spinner_message": "Running...",
        "success_message": "You can play the animation from the ▶ button at the bottom left of the screen.",
        "simulation_button": "Run Simulation",
    },
}
